version: '3'

services:
  ubuntu:
    build:
      context: ./ubuntu
      args:
        - TESSTRAIN_VERSION=${TESSTRAIN_VERSION}
    working_dir: /var/volume
    volumes:
      - ./volume:/var/volume
    tty: true
