version: '3'

services:
  ubuntu:
    build:
      context: ./ubuntu
      args:
        - TESSTRAIN_VERSION=${TESSTRAIN_VERSION}
    working_dir: /tesstrain
    volumes:
      - ./tesstrain:/tesstrain
    tty: true
